/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IERC20Contract } from "./IERC20";
import { IIFtsoContract } from "./IIFtso";
import { MockFtsoRegistryContract } from "./MockFtsoRegistry";
import { MockPriceSubmitterContract } from "./MockPriceSubmitter";
import { MockVoterWhitelisterContract } from "./MockVoterWhitelister";
import { MockNpmFtsoContract } from "./MockNpmFtso";
import { IFtsoGenesisContract } from "./IFtsoGenesis";
import { IFtsoRegistryGenesisContract } from "./IFtsoRegistryGenesis";
import { GovernedContract } from "./Governed";
import { GovernedBaseContract } from "./GovernedBase";
import { IICleanableContract } from "./IICleanable";
import { IIGovernanceVotePowerContract } from "./IIGovernanceVotePower";
import { IIVPContractContract } from "./IIVPContract";
import { IIVPTokenContract } from "./IIVPToken";
import { IFtsoContract } from "./IFtso";
import { IFtsoManagerContract } from "./IFtsoManager";
import { IFtsoRegistryContract } from "./IFtsoRegistry";
import { IGovernanceVotePowerContract } from "./IGovernanceVotePower";
import { IPriceSubmitterContract } from "./IPriceSubmitter";
import { IVoterWhitelisterContract } from "./IVoterWhitelister";
import { IVPContractEventsContract } from "./IVPContractEvents";
import { IVPTokenContract } from "./IVPToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IERC20"): IERC20Contract;
      require(name: "IIFtso"): IIFtsoContract;
      require(name: "MockFtsoRegistry"): MockFtsoRegistryContract;
      require(name: "MockPriceSubmitter"): MockPriceSubmitterContract;
      require(name: "MockVoterWhitelister"): MockVoterWhitelisterContract;
      require(name: "MockNpmFtso"): MockNpmFtsoContract;
      require(name: "IFtsoGenesis"): IFtsoGenesisContract;
      require(name: "IFtsoRegistryGenesis"): IFtsoRegistryGenesisContract;
      require(name: "Governed"): GovernedContract;
      require(name: "GovernedBase"): GovernedBaseContract;
      require(name: "IICleanable"): IICleanableContract;
      require(name: "IIGovernanceVotePower"): IIGovernanceVotePowerContract;
      require(name: "IIVPContract"): IIVPContractContract;
      require(name: "IIVPToken"): IIVPTokenContract;
      require(name: "IFtso"): IFtsoContract;
      require(name: "IFtsoManager"): IFtsoManagerContract;
      require(name: "IFtsoRegistry"): IFtsoRegistryContract;
      require(name: "IGovernanceVotePower"): IGovernanceVotePowerContract;
      require(name: "IPriceSubmitter"): IPriceSubmitterContract;
      require(name: "IVoterWhitelister"): IVoterWhitelisterContract;
      require(name: "IVPContractEvents"): IVPContractEventsContract;
      require(name: "IVPToken"): IVPTokenContract;
    }
  }
}

export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IIFtsoContract, IIFtsoInstance } from "./IIFtso";
export {
  MockFtsoRegistryContract,
  MockFtsoRegistryInstance,
} from "./MockFtsoRegistry";
export {
  MockPriceSubmitterContract,
  MockPriceSubmitterInstance,
} from "./MockPriceSubmitter";
export {
  MockVoterWhitelisterContract,
  MockVoterWhitelisterInstance,
} from "./MockVoterWhitelister";
export { MockNpmFtsoContract, MockNpmFtsoInstance } from "./MockNpmFtso";
export { IFtsoGenesisContract, IFtsoGenesisInstance } from "./IFtsoGenesis";
export {
  IFtsoRegistryGenesisContract,
  IFtsoRegistryGenesisInstance,
} from "./IFtsoRegistryGenesis";
export { GovernedContract, GovernedInstance } from "./Governed";
export { GovernedBaseContract, GovernedBaseInstance } from "./GovernedBase";
export { IICleanableContract, IICleanableInstance } from "./IICleanable";
export {
  IIGovernanceVotePowerContract,
  IIGovernanceVotePowerInstance,
} from "./IIGovernanceVotePower";
export { IIVPContractContract, IIVPContractInstance } from "./IIVPContract";
export { IIVPTokenContract, IIVPTokenInstance } from "./IIVPToken";
export { IFtsoContract, IFtsoInstance } from "./IFtso";
export { IFtsoManagerContract, IFtsoManagerInstance } from "./IFtsoManager";
export { IFtsoRegistryContract, IFtsoRegistryInstance } from "./IFtsoRegistry";
export {
  IGovernanceVotePowerContract,
  IGovernanceVotePowerInstance,
} from "./IGovernanceVotePower";
export {
  IPriceSubmitterContract,
  IPriceSubmitterInstance,
} from "./IPriceSubmitter";
export {
  IVoterWhitelisterContract,
  IVoterWhitelisterInstance,
} from "./IVoterWhitelister";
export {
  IVPContractEventsContract,
  IVPContractEventsInstance,
} from "./IVPContractEvents";
export { IVPTokenContract, IVPTokenInstance } from "./IVPToken";
