/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IFtsoInterface extends ethers.utils.Interface {
  functions: {
    "active()": FunctionFragment;
    "getCurrentEpochId()": FunctionFragment;
    "getCurrentPrice()": FunctionFragment;
    "getCurrentRandom()": FunctionFragment;
    "getEpochId(uint256)": FunctionFragment;
    "getEpochPrice(uint256)": FunctionFragment;
    "getEpochPriceForVoter(uint256,address)": FunctionFragment;
    "getPriceEpochConfiguration()": FunctionFragment;
    "getPriceEpochData()": FunctionFragment;
    "getRandom(uint256)": FunctionFragment;
    "symbol()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "active", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentEpochId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRandom",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochPriceForVoter",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceEpochConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceEpochData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRandom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;

  decodeFunctionResult(functionFragment: "active", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentEpochId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEpochId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEpochPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEpochPriceForVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceEpochConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceEpochData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRandom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;

  events: {
    "LowTurnout(uint256,uint256,uint256,uint256)": EventFragment;
    "PriceEpochInitializedOnFtso(uint256,uint256,uint256)": EventFragment;
    "PriceFinalized(uint256,uint256,bool,uint256,uint256,uint8,uint256)": EventFragment;
    "PriceHashSubmitted(address,uint256,bytes32,uint256)": EventFragment;
    "PriceRevealed(address,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LowTurnout"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PriceEpochInitializedOnFtso"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceFinalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceHashSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceRevealed"): EventFragment;
}

export class IFtso extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFtsoInterface;

  functions: {
    active(overrides?: CallOverrides): Promise<[boolean]>;

    getCurrentEpochId(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentPrice(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _price: BigNumber; _timestamp: BigNumber }
    >;

    getCurrentRandom(overrides?: CallOverrides): Promise<[BigNumber]>;

    getEpochId(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEpochPrice(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEpochPriceForVoter(
      _epochId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceEpochConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _firstEpochStartTime: BigNumber;
        _submitPeriod: BigNumber;
        _revealPeriod: BigNumber;
      }
    >;

    getPriceEpochData(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        _epochId: BigNumber;
        _epochSubmitEndTime: BigNumber;
        _epochRevealEndTime: BigNumber;
        _votePowerBlock: BigNumber;
        _fallbackMode: boolean;
      }
    >;

    getRandom(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;
  };

  active(overrides?: CallOverrides): Promise<boolean>;

  getCurrentEpochId(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentPrice(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { _price: BigNumber; _timestamp: BigNumber }
  >;

  getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

  getEpochId(
    _timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEpochPrice(
    _epochId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEpochPriceForVoter(
    _epochId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceEpochConfiguration(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      _firstEpochStartTime: BigNumber;
      _submitPeriod: BigNumber;
      _revealPeriod: BigNumber;
    }
  >;

  getPriceEpochData(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      _epochId: BigNumber;
      _epochSubmitEndTime: BigNumber;
      _epochRevealEndTime: BigNumber;
      _votePowerBlock: BigNumber;
      _fallbackMode: boolean;
    }
  >;

  getRandom(
    _epochId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  symbol(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    active(overrides?: CallOverrides): Promise<boolean>;

    getCurrentEpochId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPrice(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { _price: BigNumber; _timestamp: BigNumber }
    >;

    getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

    getEpochId(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEpochPrice(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEpochPriceForVoter(
      _epochId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceEpochConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _firstEpochStartTime: BigNumber;
        _submitPeriod: BigNumber;
        _revealPeriod: BigNumber;
      }
    >;

    getPriceEpochData(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        _epochId: BigNumber;
        _epochSubmitEndTime: BigNumber;
        _epochRevealEndTime: BigNumber;
        _votePowerBlock: BigNumber;
        _fallbackMode: boolean;
      }
    >;

    getRandom(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    LowTurnout(
      epochId?: BigNumberish | null,
      natTurnout?: null,
      lowNatTurnoutThresholdBIPS?: null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, BigNumber],
      {
        epochId: BigNumber;
        natTurnout: BigNumber;
        lowNatTurnoutThresholdBIPS: BigNumber;
        timestamp: BigNumber;
      }
    >;

    PriceEpochInitializedOnFtso(
      epochId?: BigNumberish | null,
      endTime?: null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { epochId: BigNumber; endTime: BigNumber; timestamp: BigNumber }
    >;

    PriceFinalized(
      epochId?: BigNumberish | null,
      price?: null,
      rewardedFtso?: null,
      lowRewardPrice?: null,
      highRewardPrice?: null,
      finalizationType?: null,
      timestamp?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, boolean, BigNumber, BigNumber, number, BigNumber],
      {
        epochId: BigNumber;
        price: BigNumber;
        rewardedFtso: boolean;
        lowRewardPrice: BigNumber;
        highRewardPrice: BigNumber;
        finalizationType: number;
        timestamp: BigNumber;
      }
    >;

    PriceHashSubmitted(
      submitter?: string | null,
      epochId?: BigNumberish | null,
      hash?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      {
        submitter: string;
        epochId: BigNumber;
        hash: string;
        timestamp: BigNumber;
      }
    >;

    PriceRevealed(
      voter?: string | null,
      epochId?: BigNumberish | null,
      price?: null,
      random?: null,
      timestamp?: null,
      votePowerNat?: null,
      votePowerAsset?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        voter: string;
        epochId: BigNumber;
        price: BigNumber;
        random: BigNumber;
        timestamp: BigNumber;
        votePowerNat: BigNumber;
        votePowerAsset: BigNumber;
      }
    >;
  };

  estimateGas: {
    active(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentEpochId(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentRandom(overrides?: CallOverrides): Promise<BigNumber>;

    getEpochId(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEpochPrice(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEpochPriceForVoter(
      _epochId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceEpochConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getPriceEpochData(overrides?: CallOverrides): Promise<BigNumber>;

    getRandom(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    active(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentEpochId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentRandom(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEpochId(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEpochPrice(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEpochPriceForVoter(
      _epochId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceEpochConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceEpochData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRandom(
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
