/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IFtsoGenesisInterface extends ethers.utils.Interface {
  functions: {
    "revealPriceSubmitter(address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "submitPriceHashSubmitter(address,uint256,bytes32)": FunctionFragment;
    "wNatVotePowerCached(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "revealPriceSubmitter",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPriceHashSubmitter",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wNatVotePowerCached",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "revealPriceSubmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPriceHashSubmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wNatVotePowerCached",
    data: BytesLike
  ): Result;

  events: {};
}

export class IFtsoGenesis extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFtsoGenesisInterface;

  functions: {
    revealPriceSubmitter(
      _voter: string,
      _epochId: BigNumberish,
      _price: BigNumberish,
      _random: BigNumberish,
      _wNatVP: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitPriceHashSubmitter(
      _sender: string,
      _epochId: BigNumberish,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wNatVotePowerCached(
      _voter: string,
      _epochId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  revealPriceSubmitter(
    _voter: string,
    _epochId: BigNumberish,
    _price: BigNumberish,
    _random: BigNumberish,
    _wNatVP: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitPriceHashSubmitter(
    _sender: string,
    _epochId: BigNumberish,
    _hash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wNatVotePowerCached(
    _voter: string,
    _epochId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    revealPriceSubmitter(
      _voter: string,
      _epochId: BigNumberish,
      _price: BigNumberish,
      _random: BigNumberish,
      _wNatVP: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitPriceHashSubmitter(
      _sender: string,
      _epochId: BigNumberish,
      _hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    wNatVotePowerCached(
      _voter: string,
      _epochId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    revealPriceSubmitter(
      _voter: string,
      _epochId: BigNumberish,
      _price: BigNumberish,
      _random: BigNumberish,
      _wNatVP: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitPriceHashSubmitter(
      _sender: string,
      _epochId: BigNumberish,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wNatVotePowerCached(
      _voter: string,
      _epochId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    revealPriceSubmitter(
      _voter: string,
      _epochId: BigNumberish,
      _price: BigNumberish,
      _random: BigNumberish,
      _wNatVP: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitPriceHashSubmitter(
      _sender: string,
      _epochId: BigNumberish,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wNatVotePowerCached(
      _voter: string,
      _epochId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
