/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IIVPContractInterface extends ethers.utils.Interface {
  functions: {
    "batchVotePowerOfAt(address[],uint256)": FunctionFragment;
    "cleanupBlockNumber()": FunctionFragment;
    "delegate(address,address,uint256,uint256)": FunctionFragment;
    "delegateExplicit(address,address,uint256,uint256)": FunctionFragment;
    "delegatesOf(address)": FunctionFragment;
    "delegatesOfAt(address,uint256)": FunctionFragment;
    "delegationModeOf(address)": FunctionFragment;
    "isReplacement()": FunctionFragment;
    "ownerToken()": FunctionFragment;
    "revokeDelegationAt(address,address,uint256,uint256)": FunctionFragment;
    "setCleanerContract(address)": FunctionFragment;
    "setCleanupBlockNumber(uint256)": FunctionFragment;
    "setCleanupBlockNumberManager(address)": FunctionFragment;
    "undelegateAll(address,uint256)": FunctionFragment;
    "undelegateAllExplicit(address,address[])": FunctionFragment;
    "undelegatedVotePowerOf(address,uint256)": FunctionFragment;
    "undelegatedVotePowerOfAt(address,uint256,uint256)": FunctionFragment;
    "updateAtTokenTransfer(address,address,uint256,uint256,uint256)": FunctionFragment;
    "votePowerFromTo(address,address,uint256)": FunctionFragment;
    "votePowerFromToAt(address,address,uint256,uint256)": FunctionFragment;
    "votePowerOf(address)": FunctionFragment;
    "votePowerOfAt(address,uint256)": FunctionFragment;
    "votePowerOfAtCached(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "batchVotePowerOfAt",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cleanupBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delegate",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateExplicit",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "delegatesOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "delegatesOfAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegationModeOf",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isReplacement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegationAt",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCleanerContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCleanupBlockNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCleanupBlockNumberManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateAll",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateAllExplicit",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegatedVotePowerOf",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegatedVotePowerOfAt",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAtTokenTransfer",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerFromTo",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerFromToAt",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "votePowerOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "votePowerOfAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votePowerOfAtCached",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchVotePowerOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cleanupBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateExplicit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatesOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegationModeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReplacement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegationAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCleanerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCleanupBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCleanupBlockNumberManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateAllExplicit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegatedVotePowerOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegatedVotePowerOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAtTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerFromTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerFromToAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votePowerOfAtCached",
    data: BytesLike
  ): Result;

  events: {
    "Delegate(address,address,uint256,uint256)": EventFragment;
    "Revoke(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Delegate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoke"): EventFragment;
}

export class IIVPContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IIVPContractInterface;

  functions: {
    batchVotePowerOfAt(
      _owners: string[],
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    cleanupBlockNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    delegate(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _bips: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    delegateExplicit(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    delegatesOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber, BigNumber] & {
        _delegateAddresses: string[];
        _bips: BigNumber[];
        _count: BigNumber;
        _delegationMode: BigNumber;
      }
    >;

    delegatesOfAt(
      _owner: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber, BigNumber] & {
        _delegateAddresses: string[];
        _bips: BigNumber[];
        _count: BigNumber;
        _delegationMode: BigNumber;
      }
    >;

    delegationModeOf(
      _who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isReplacement(overrides?: CallOverrides): Promise<[boolean]>;

    ownerToken(overrides?: CallOverrides): Promise<[string]>;

    revokeDelegationAt(
      _from: string,
      _who: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCleanerContract(
      _cleanerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCleanupBlockNumber(
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCleanupBlockNumberManager(
      _cleanupBlockNumberManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    undelegateAll(
      _from: string,
      _balance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    undelegateAllExplicit(
      _from: string,
      _delegateAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    undelegatedVotePowerOf(
      _owner: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    undelegatedVotePowerOfAt(
      _owner: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    updateAtTokenTransfer(
      _from: string,
      _to: string,
      _fromBalance: BigNumberish,
      _toBalance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    votePowerFromTo(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    votePowerFromToAt(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    votePowerOf(_who: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    votePowerOfAt(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    votePowerOfAtCached(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  batchVotePowerOfAt(
    _owners: string[],
    _blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  cleanupBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

  delegate(
    _from: string,
    _to: string,
    _balance: BigNumberish,
    _bips: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  delegateExplicit(
    _from: string,
    _to: string,
    _balance: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  delegatesOf(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[], BigNumber, BigNumber] & {
      _delegateAddresses: string[];
      _bips: BigNumber[];
      _count: BigNumber;
      _delegationMode: BigNumber;
    }
  >;

  delegatesOfAt(
    _owner: string,
    _blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[], BigNumber, BigNumber] & {
      _delegateAddresses: string[];
      _bips: BigNumber[];
      _count: BigNumber;
      _delegationMode: BigNumber;
    }
  >;

  delegationModeOf(_who: string, overrides?: CallOverrides): Promise<BigNumber>;

  isReplacement(overrides?: CallOverrides): Promise<boolean>;

  ownerToken(overrides?: CallOverrides): Promise<string>;

  revokeDelegationAt(
    _from: string,
    _who: string,
    _balance: BigNumberish,
    _blockNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCleanerContract(
    _cleanerContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCleanupBlockNumber(
    _blockNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCleanupBlockNumberManager(
    _cleanupBlockNumberManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  undelegateAll(
    _from: string,
    _balance: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  undelegateAllExplicit(
    _from: string,
    _delegateAddresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  undelegatedVotePowerOf(
    _owner: string,
    _balance: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  undelegatedVotePowerOfAt(
    _owner: string,
    _balance: BigNumberish,
    _blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateAtTokenTransfer(
    _from: string,
    _to: string,
    _fromBalance: BigNumberish,
    _toBalance: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  votePowerFromTo(
    _from: string,
    _to: string,
    _balance: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  votePowerFromToAt(
    _from: string,
    _to: string,
    _balance: BigNumberish,
    _blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  votePowerOf(_who: string, overrides?: CallOverrides): Promise<BigNumber>;

  votePowerOfAt(
    _who: string,
    _blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  votePowerOfAtCached(
    _who: string,
    _blockNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchVotePowerOfAt(
      _owners: string[],
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    cleanupBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _bips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    delegateExplicit(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    delegatesOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber, BigNumber] & {
        _delegateAddresses: string[];
        _bips: BigNumber[];
        _count: BigNumber;
        _delegationMode: BigNumber;
      }
    >;

    delegatesOfAt(
      _owner: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber, BigNumber] & {
        _delegateAddresses: string[];
        _bips: BigNumber[];
        _count: BigNumber;
        _delegationMode: BigNumber;
      }
    >;

    delegationModeOf(
      _who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isReplacement(overrides?: CallOverrides): Promise<boolean>;

    ownerToken(overrides?: CallOverrides): Promise<string>;

    revokeDelegationAt(
      _from: string,
      _who: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCleanerContract(
      _cleanerContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCleanupBlockNumber(
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCleanupBlockNumberManager(
      _cleanupBlockNumberManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    undelegateAll(
      _from: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    undelegateAllExplicit(
      _from: string,
      _delegateAddresses: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    undelegatedVotePowerOf(
      _owner: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    undelegatedVotePowerOfAt(
      _owner: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAtTokenTransfer(
      _from: string,
      _to: string,
      _fromBalance: BigNumberish,
      _toBalance: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    votePowerFromTo(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerFromToAt(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerOf(_who: string, overrides?: CallOverrides): Promise<BigNumber>;

    votePowerOfAt(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerOfAtCached(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Delegate(
      from?: string | null,
      to?: string | null,
      priorVotePower?: null,
      newVotePower?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        from: string;
        to: string;
        priorVotePower: BigNumber;
        newVotePower: BigNumber;
      }
    >;

    Revoke(
      delegator?: string | null,
      delegatee?: string | null,
      votePower?: null,
      blockNumber?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        delegator: string;
        delegatee: string;
        votePower: BigNumber;
        blockNumber: BigNumber;
      }
    >;
  };

  estimateGas: {
    batchVotePowerOfAt(
      _owners: string[],
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cleanupBlockNumber(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _bips: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    delegateExplicit(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    delegatesOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    delegatesOfAt(
      _owner: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegationModeOf(
      _who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isReplacement(overrides?: CallOverrides): Promise<BigNumber>;

    ownerToken(overrides?: CallOverrides): Promise<BigNumber>;

    revokeDelegationAt(
      _from: string,
      _who: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCleanerContract(
      _cleanerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCleanupBlockNumber(
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCleanupBlockNumberManager(
      _cleanupBlockNumberManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    undelegateAll(
      _from: string,
      _balance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    undelegateAllExplicit(
      _from: string,
      _delegateAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    undelegatedVotePowerOf(
      _owner: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    undelegatedVotePowerOfAt(
      _owner: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAtTokenTransfer(
      _from: string,
      _to: string,
      _fromBalance: BigNumberish,
      _toBalance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    votePowerFromTo(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerFromToAt(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerOf(_who: string, overrides?: CallOverrides): Promise<BigNumber>;

    votePowerOfAt(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votePowerOfAtCached(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchVotePowerOfAt(
      _owners: string[],
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cleanupBlockNumber(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegate(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _bips: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    delegateExplicit(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    delegatesOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegatesOfAt(
      _owner: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegationModeOf(
      _who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isReplacement(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revokeDelegationAt(
      _from: string,
      _who: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCleanerContract(
      _cleanerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCleanupBlockNumber(
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCleanupBlockNumberManager(
      _cleanupBlockNumberManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    undelegateAll(
      _from: string,
      _balance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    undelegateAllExplicit(
      _from: string,
      _delegateAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    undelegatedVotePowerOf(
      _owner: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    undelegatedVotePowerOfAt(
      _owner: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAtTokenTransfer(
      _from: string,
      _to: string,
      _fromBalance: BigNumberish,
      _toBalance: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    votePowerFromTo(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePowerFromToAt(
      _from: string,
      _to: string,
      _balance: BigNumberish,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePowerOf(
      _who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePowerOfAt(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votePowerOfAtCached(
      _who: string,
      _blockNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
